#!/bin/bash
#SBATCH -c 1
#SBATCH -t 0-6:00
#SBATCH --mem=8G
#SBATCH -p bch-compute
#SBATCH -o L1_CL_DoxOrf_Dox_A8_refine_%j.out

perl /home/ch237385/bin/BCH/method_development/check_polyA_from_sam.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/tmp/L1_CL_DoxOrf_Dox_A8.bam.clipped.sam_partial_polyA.sam /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/tmp/L1_CL_DoxOrf_Dox_A8.bam.clipped.sam.sam /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam
perl /home/ch237385/bin/BCH/method_development/add_disc_info_at_candidate_list_from_clip.txt_tmp.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/tmp/raw_discordant_reads_tmp0_seplf /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam.add_disc
perl /home/ch237385/bin/BCH/method_development/add_polyA_info_again.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1_add_polyA_at_clip_stp/candidate_list_from_clip.txt_tmp /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam.add_disc > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam.add_disc.add_xTea_polyA
perl -lane 'next if /merged_in_peak/; if(/lclip_cnt/){print "type1/2\t$_"; next}; if(($F[5]>0 || $F[6]>0) && ($F[12]>0 || $F[13]>0)){print "type1\t$_"}elsif(($F[5]+$F[6]+$F[12]+$F[13])>=6){print "type2\t$_"}' /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_clip.txt_tmp.add_polyA_from_sam.add_disc.add_xTea_polyA | sort > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt
perl /home/ch237385/bin/BCH/method_development/extend_to_ORFeus/cal_realign_cnt_2-types.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/tmp/L1_CL_DoxOrf_Dox_A8.bam.clipped.sam > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio
perl -lane 'if(/lclip_cnt/){print;next} my @a=split /,/, $F[8]; my $ratio=$a[2]; if(($F[0] eq "type1") && ($ratio>=0.6)){print}' /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt
perl /home/ch237385/bin/BCH/method_development/extend_to_ORFeus/pair_the_end_points.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/candidate_list_from_disc.txt /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine
perl /home/ch237385/bin/BCH/method_development/check_ref_repeat_for_somatic_L1.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/ref/repeat_masker/hg38_repeat_masker.tsv.sort /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.add_ref_repeat
perl /home/ch237385/bin/BCH/method_development/extend_to_ORFeus/add_more_candidate_from_vcf.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.add_ref_repeat /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/L1_CL_DoxOrf_Dox_A8_LINE1.vcf > /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine2
perl /home/ch237385/bin/BCH/method_development/extend_to_ORFeus/get_somatic_event.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/DMSO.cns.txt.list /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine2 /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.somatic /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.shared_with_DMSO
perl /home/ch237385/bin/BCH/method_development/extend_to_ORFeus/get_somatic_event_absent_in_all_samples.pl /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/DMSO_DoX.candidate_disc_filtered_cns.txt.list /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.somatic /lab-share/Gene-Lee-e2/Public/home/xizeng/project/xTea/ORFeus_Dox_L1_ins/backup/L1_CL_DoxOrf_Dox_A8/L1/ORFeus_insertion.2-types.txt.add_clip_ORFeus_ratio.flt.refine.somatic-5.2_absent_from_all_samples
